import ts from 'typescript';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const src = ts.transpileModule(fs.readFileSync(new URL('../src/lib/rewards.ts', import.meta.url), 'utf8'), { compilerOptions: { module: 1 } }).outputText;
const m = { exports: {} }; new Function('module', 'exports', src)(m, m.exports);
const { emptyState, claim, claimable, exchange, useCoupon, earnedFor } = m.exports;
let s = emptyState(); const D1 = '2026-10-08', D2 = '2026-10-09';
assert.equal(earnedFor(999), 0); assert.equal(earnedFor(1000), 1); assert.equal(earnedFor(12345), 5); assert.equal(earnedFor(-5), 0);
let r = claim(s, D1, 2800); assert.equal(r.added, 2); s = r.state;
r = claim(s, D1, 2800); assert.equal(r.added, 0, '같은 걸음 재조회 중복 지급 없음');
r = claim(s, D1, 1500); assert.equal(r.added, 0, '걸음 감소 시 음수 지급 없음'); assert.equal(r.state.balance, 2);
r = claim(s, D1, 9000); assert.equal(r.added, 3, '하루 최대 5개'); s = r.state;
assert.equal(claimable(s, D1, 20000), 0);
r = claim(s, D2, 4200); assert.equal(r.added, 4, '날짜 바뀌면 한도 초기화'); s = r.state; assert.equal(s.balance, 9, '잔액 이월');
let x = exchange(s, 'store-a', 'c1'); assert.equal(x.coupon, null, '잔액 부족 교환 차단'); assert.equal(x.state.balance, 9);
s = claim(s, D2, 5000).state; assert.equal(s.balance, 10);
x = exchange(s, 'store-a', 'c1'); assert.ok(x.coupon); s = x.state; assert.equal(s.balance, 0); assert.equal(s.coupons.length, 1);
let u = useCoupon(s, 'c1'); assert.ok(u.ok); s = u.state;
u = useCoupon(s, 'c1'); assert.equal(u.ok, false, '사용한 쿠폰 재사용 차단');
s = emptyState(); s.balance = 10;
x = exchange(s, 'store-b', 'c2', new Date('2026-10-01T00:00:00Z'), 7); s = x.state;
assert.equal(useCoupon(s, 'c2', new Date('2026-10-09T00:00:00Z')).ok, false, '유효기간 지난 쿠폰 사용 차단');
assert.equal(useCoupon(s, 'c2', new Date('2026-10-05T00:00:00Z')).ok, true, '유효기간 안 쿠폰 사용');
console.log('모든 보상 규칙 테스트 통과 (13개 확인)');
